[package]
name = "guac-light-client"
version = "0.1.0"
authors = ["Jehan <jehan.tremback@gmail.com>"]

[dependencies]
bigint = "*"
rand = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
serde_bytes = "*"
base64 = "*"
rocksdb = "0.8.1"
syn = "*"
quote = "*"
array_serialization_derive = { path = "../array_serialization_derive" }
derive-error = "*"
tiny-keccak = "1.3"
num = "*"
lazy_static ="*"
