[package]
name = "althea_rs"
version = "0.1.7"
authors = ["Stan Drozd <drozdziak1@gmail.com>"]

[features]
default = []
development = ["rita/development"]
guac = ["rita/guac"]

[dependencies]
rita = { path = "./rita" }

[workspace]
members = ["althea_kernel_interface", "settings", "clu", "exit_db", "num256", "babel_monitor"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
incremental = false

[patch.'https://github.com/althea-mesh/althea_rs.git']
num256 = {path = "./num256"}
althea_types = {path = "./althea_types"}
