[package]
name = "althea_rs"
version = "0.1.11"
authors = ["Stan Drozd <drozdziak1@gmail.com>"]
edition = "2018"

[features]
development = ["rita/development"]
server = ["rita/server"]

[dependencies]
rita = { path = "./rita" }

[workspace]
members = ["althea_kernel_interface", "settings", "clu", "exit_db", "fastping_rs"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
incremental = false

[patch.crates-io]
