[package]
name = "althea_rs"
version = "0.1.3"
authors = ["Stan Drozd <drozdziak1@gmail.com>"]

[dependencies]
rita = { path = "./rita" }

[workspace]
members = ["althea_kernel_interface", "bounty_hunter", "settings", "clu", "exit_db", "stats_server"]

[profile.release]
opt-level = "z"
debug=true
lto = true
codegen-units = 1
incremental = false

[patch.crates-io]
actix = { git = "https://github.com/kingoflolz/actix.git", branch = "althea-mesh" }
actix-web = { git = "https://github.com/actix/actix-web.git", branch = "fix-missing-content-length" }
trust-dns-resolver = { git = "https://github.com/kingoflolz/trust-dns.git", branch = "lower-max-ttl" }
