[package]
name = "althea_rs"
version = "0.1.9"
authors = ["Stan Drozd <drozdziak1@gmail.com>"]

[features]
development = ["rita/development"]

[dependencies]
rita = { path = "./rita" }

[workspace]
members = ["althea_kernel_interface", "bounty_hunter", "settings", "clu", "exit_db"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
incremental = false

[patch.crates-io]
