[package]
name = "rita"
version = "0.1.0"
authors = ["Jehan <jehan.tremback@gmail.com>"]

[dependencies]
babel_monitor = { path = "../babel_monitor" }
althea_types = { path = "../althea_types" }
althea_kernel_interface = { path = "../althea_kernel_interface" }
num256 = { path = "../num256" }
ip_network = "0.1"
log = "0.3"
simple_logger = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.8"
rand = "*"
lazy_static = "1.0"
actix = {git="https://github.com/actix/actix.git"}
actix_derive = {git="https://github.com/actix/actix-derive.git"}
actix-web = {git="https://github.com/actix/actix-web.git"}
config = "0.8.0"
eui48 = {git="https://github.com/althea-mesh/eui48.git"}
minihttpse = "0.1.6"
docopt = "0.8.3"
derive-error = "0.0.4"
futures = "0.1"
mockito = "0.9"
bytes = "0.4"