[package]
name = "rita"
version = "0.2.0"
authors = ["Jehan <jehan.tremback@gmail.com>", "Ben <wangben3@gmail.com>"]
build = "build.rs"
[[bin]]
name = "rita_exit"
path = "src/exit.rs"

[[bin]]
name = "rita"
path = "src/client.rs"

[dependencies]
althea_kernel_interface = { path = "../althea_kernel_interface" }
althea_types = { path = "../althea_types", features = ["actix"]}
babel_monitor = { path = "../babel_monitor" }
clu = { path = "../clu" }
exit_db = { path = "../exit_db" }
num256 = "0.1"
settings = { path = "../settings" }

guac_core = {path = "/home/justin/repos/guac_rs/guac_core"}
syslog = "4.0"
actix = "0.7.4"
actix-web = { version = "0.7.4", default_features = false }
actix_derive = "0.3.0"
bytes = "0.4.10"
config = "0.9.0"
diesel = { version = "1.3.3", features = ["sqlite"] }
libsqlite3-sys = { version = "0.9.3", features = ["bundled"] }
docopt = "0.8.3"
dotenv = "0.13.0"
env_logger = "0.6.0"
failure = "0.1.3"
futures = "0.1.25"
handlebars = "1.1.0"
ipnetwork = "0.13.1"
lazy_static = "1.2.0"
log = "0.4.6"
minihttpse = "0.1.6"
mockito = "0.13.0"
num-traits = "0.2.6"
openssl-probe = "0.1.2"
rand = "0.6.0"
regex = "1.0.6"
reqwest = "0.9.5"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
tokio = "0.1.11"
tokio-codec = "0.1.1"
tokio-io = "0.1.10"
trust-dns-resolver = "0.10.0"

[features]
default = []
development = []
system_alloc = []
