[package]
name = "rita"
version = "0.1.0"
authors = ["Jehan <jehan.tremback@gmail.com>"]

[dependencies]
babel_monitor = { path = "../babel_monitor" }
althea_types = { path = "../althea_types" }
althea_kernel_interface = { path = "../althea_kernel_interface" }
traffic_watcher = { path = "./traffic_watcher"}
payment_controller = { path = "./payment_controller" }
debt_keeper = { path = "./debt_keeper" }
tunnel_manager = { path = "./tunnel_manager" }
num256 = { path = "../num256" }
ip_network = "0.1"
log = "0.3"
docopt = "0.8.1"
simple_logger = "0.4.0"
rouille = "1.0.3"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"
reqwest = "0.8.2"
rand = "*"
config = "0.8"