[package]
name = "althea_kernel_interface"
version = "0.1.0"
authors = ["Jehan <jehan.tremback@gmail.com>"]
description = "Gets information from and changes settings of kernel network stacks"
license = "Apache-2.0"

[dependencies]
regex = "0.2"
failure = "0.1.1"
itertools = "0.7.4"
log = "0.3"
lazy_static = "1.0"
eui48 = { git = "https://github.com/althea-mesh/eui48", features = ["serde"] }
