[package]
name = "payment_controller"
version = "0.1.0"
authors = ["Jehan <jehan.tremback@gmail.com>"]
license = "Apache 2.0"

[dependencies]
althea_types = { path = "../../althea_types" }
num256 =  { path = "../../num256" }
debt_keeper = { path = "../debt_keeper" }
settings = { path = "../settings" }
rouille = "1.0.3"
reqwest = "0.8.2"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"
derive-error = "0.0.4"
log = "0.3"
eui48 = { git = "https://github.com/althea-mesh/eui48", features = ["serde"] }
mockito = "0.9.0"