[package]
authors = ["Jehan <jehan.tremback@gmail.com>"]
name = "althea_types"
version = "0.1.0"
edition = "2018"

[dependencies]
num256 = "0.2"
base64 = "0.10"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
hex = "0.4"
sodiumoxide = "0.2"
eui48 = { git = "https://github.com/althea-mesh/eui48", features = ["serde"] }
actix = { version = "0.7", optional = true}
clarity = "0.1"
arrayvec = {version= "0.5", features = ["serde"]}

