[package]
name = "althea_types"
version = "0.1.0"
authors = ["Jehan <jehan.tremback@gmail.com>"]

[dependencies]
num256 = { path = "../num256" }
base64 = "0.9.3"
serde_derive = "1.0.79"
serde = "1.0.79"
serde_json = "1.0.28"
hex = "0.3.2"
eui48 = { git = "https://github.com/althea-mesh/eui48", features = ["serde"] }
actix = { version = "0.7.4", optional = true}
ethereum-types = "0.4.0"
num-bigint = { version = "0.2", features = ["serde"] }
clarity = "0.1"
