[package]
name = "tunnel_manager"
version = "0.1.0"
authors = ["Jehan <jehan.tremback@gmail.com>"]

[dependencies]
althea_kernel_interface = { path = "../../althea_kernel_interface" }
althea_types = { path = "../../althea_types" }
debt_keeper = { path = "../debt_keeper"}
reqwest = "0.8.2"
derive-error = "0.0.4"