[package]
authors = ["Justin <kilpatrickjustin@protonmail.ch>"]
name = "clu"
version = "0.0.1"
edition = "2018"

[dependencies]
settings = { path = "../settings" }
althea_kernel_interface = { path = "../althea_kernel_interface" }
althea_types = { path = "../althea_types" }
babel_monitor = { path = "../babel_monitor" }
lazy_static = "1.3"
log = "0.4"
env_logger = "0.6"
failure = "0.1"
ipgen = "0.0.4"
regex = "1.1"
rand = "0.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clarity = "0.1"
futures = "0.1"
