[package]
authors = ["Justin <kilpatrickjustin@protonmail.ch>"]
name = "clu"
version = "0.0.1"

[dependencies]
settings = { path = "../settings" }
althea_kernel_interface = { path = "../althea_kernel_interface" }
althea_types = { path = "../althea_types" }
babel_monitor = { path = "../babel_monitor" }
lazy_static = "1.1.0"
log = "0.4.5"
env_logger = "0.5.13"
failure = "0.1.2"
ipgen = "0.0.4"
regex = "1.0.5"
rand = "0.5.5"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.28"
clarity = {path = "../../clarity"}
