name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install cross
        run: cargo install cross
      - name: Test Rita and Rita Exit x86
        run: cargo build --all && RUST_TEST_THREADS=1 cargo test --verbose --all
      - name: Cross test x86_64
        run: cross test --target x86_64-unknown-linux-musl --verbose -p rita --bin rita --features bundle_openssl -- --test-threads=1
      - name: Cross test mips
        run: cross test --target mips-unknown-linux-musl --verbose -p rita --bin rita --features bundle_openssl -- --test-threads=1
      - name: Cross test mipsel
        run: cross test --target mipsel-unknown-linux-musl --verbose -p rita --bin rita --features bundle_openssl -- --test-threads=1
      - name: Cross test mips64
        run: cross test --target mips64-unknown-linux-gnuabi64 --verbose -p rita --bin rita --features bundle_openssl -- --test-threads=1
      - name: Cross test mips64el
        run: cross test --target mips64el-unknown-linux-gnuabi64 --verbose -p rita --bin rita --features bundle_openssl -- --test-threads=1
      - name: Cross test aarch64
        run: cross test --target aarch64-unknown-linux-musl --verbose -p rita --bin rita --features bundle_openssl -- --test-threads=1
      - name: Cross test armv7
        run: cross test --target armv7-unknown-linux-musleabihf --verbose -p rita --bin rita --features bundle_openssl -- --test-threads=1
